---
abstract: 'Find or build libevent'
author:
  - 'Thibault Duponchelle <thibault.duponchelle@gmail.com>'
build_requires:
  Alien::Build::MM: '0.25'
  Alien::OpenSSL: '0'
  Archive::Tar: '0'
  Config: '0'
  Env::ShellWords: '0.01'
  HTTP::Tiny: '0.044'
  IO::Socket::SSL: '1.56'
  Mojo::DOM58: '1.00'
  Net::SSLeay: '1.49'
  Sort::Versions: '0'
  URI: '0'
  URI::Escape: '0'
configure_requires:
  Alien::Build: '1.19'
  Alien::Build::MM: '0.25'
  Alien::Build::Plugin::Build::SearchDep: '0.35'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.4702, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Libevent
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Base: '0.038'
  Alien::Build: '0.25'
  Test::Alien: '0'
  Test::Alien::Diag: '0'
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: https://github.com/thibaultduponchelle/Alien-Libevent/issues
  homepage: https://metacpan.org/release/Alien-Libevent
  license: http://dev.perl.org/licenses/
  repository: https://github.com/thibaultduponchelle/Alien-Libevent.git
version: '2.8'
x_alienfile:
  generated_by: 'Alien::Build::MM version 2.26'
  requires:
    share:
      Alien::OpenSSL: '0'
      Archive::Tar: '0'
      Config: '0'
      Env::ShellWords: '0.01'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      Mojo::DOM58: '1.00'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
