name = "Test-Slow"
badges = ["github-actions/linux", "github-actions/macos", "github-actions/windows", "kritika"]
module_maker="ModuleBuildTiny"
static_install = "auto"
markdown_maker="Pod::Markdown::Github"
