name = "Test-Slow"
badges = ["github-actions/linux", "github-actions/macos", "github-actions/windows"]
module_maker="ModuleBuildTiny"
static_install = "auto"
#readme_from="lib/XML/Minify.pm"
markdown_maker="Pod::Markdown::Github"
