---
abstract: 'A configurable XML minifier.'
author:
  - 'Thibault DUPONCHELLE <thibault.duponchelle@gmail.com>'
build_requires:
  Test::More: '0'
  Test::Slow: '0.04'
  XML::LibXML: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4232, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Minifier
provides:
  XML::Minifier:
    file: lib/XML/Minifier.pm
    version: '1.03'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '1.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
