---
abstract: 'Embarrassing the MetaCPAN Markdown converter'
author:
  - 'Thibault DUPONCHELLE <thibault.duponchelle@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Markdown-Embarrassing
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
resources:
  repository: https://github.com/thibaultduponchelle/CPAN-modules/Acme-Markdown-Embarrassing
version: '3.2'
x_homepage: https://github.com/thibaultduponchelle/CPAN-modules/Acme-Markdown-Embarrassing
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
